# Generated by Django 5.2.13 on 2026-04-25 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('portfolios', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('acquisition', 'Acquisition'), ('disposition', 'Disposition'), ('optimization', 'Optimization'), ('risk', 'Risk')], max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='open', max_length=16)),
                ('expected_roi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='properties.propertyasset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='organizations.organization')),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('market', 'Market'), ('portfolio', 'Portfolio'), ('financial', 'Financial'), ('risk', 'Risk')], max_length=32)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('archived', 'Archived')], default='ready', max_length=16)),
                ('file_url', models.URLField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='properties.propertyasset')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='organizations.organization')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('strategy', models.CharField(choices=[('long_term', 'Longue duree'), ('seasonal', 'Saisonnier'), ('flip', 'Achat revente')], max_length=32)),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('loan_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('loan_years', models.PositiveIntegerField(default=20)),
                ('renovation_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('holding_period_years', models.PositiveIntegerField(default=10)),
                ('projected_monthly_cashflow', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('projected_irr', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('projected_exit_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('assumptions', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='properties.propertyasset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('completed', 'Complete')], default='completed', max_length=20)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('low_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('high_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('model_version', models.CharField(default='v1', max_length=64)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuations', to='properties.propertyasset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='organizations.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
