# Generated by Django 5.2.13 on 2026-04-25 22:08
# Migration initiale des portefeuilles et des positions.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('strategy', models.CharField(blank=True, max_length=255)),
                ('benchmark_return', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('target_occupancy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('currency', models.CharField(default='MAD', max_length=8)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation_share', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='properties.propertyasset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['portfolio__name', 'asset__name'],
                'unique_together': {('portfolio', 'asset')},
            },
        ),
    ]
