# Generated by Codex on 2026-04-30
# Migration ajoutant le modele de listings de marche importes.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketListing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(choices=[("avito", "Avito"), ("mubawab", "Mubawab")], max_length=32)),
                ("source_id", models.CharField(blank=True, max_length=120)),
                ("external_url", models.URLField(max_length=1000)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Appartement"),
                            ("villa", "Villa"),
                            ("office", "Bureau"),
                            ("retail", "Retail"),
                            ("land", "Terrain"),
                            ("hospitality", "Hospitality"),
                            ("unknown", "Inconnu"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("sale", "Vente"),
                            ("rent", "Location"),
                            ("vacation", "Location courte duree"),
                            ("unknown", "Inconnu"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=120)),
                ("district", models.CharField(blank=True, max_length=120)),
                ("price", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("currency", models.CharField(default="MAD", max_length=8)),
                ("price_period", models.CharField(blank=True, max_length=32)),
                ("area_sqm", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("bedrooms", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("bathrooms", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("seller_name", models.CharField(blank=True, max_length=255)),
                ("published_label", models.CharField(blank=True, max_length=120)),
                ("scraped_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-last_seen_at", "source", "title"],
            },
        ),
        migrations.AddConstraint(
            model_name="marketlisting",
            constraint=models.UniqueConstraint(fields=("source", "external_url"), name="uniq_market_listing_source_url"),
        ),
        migrations.AddIndex(
            model_name="marketlisting",
            index=models.Index(fields=["source", "last_seen_at"], name="properties__source_341c41_idx"),
        ),
        migrations.AddIndex(
            model_name="marketlisting",
            index=models.Index(fields=["city", "district"], name="properties__city_5e298e_idx"),
        ),
        migrations.AddIndex(
            model_name="marketlisting",
            index=models.Index(fields=["asset_type", "transaction_type"], name="properties__asset_t_3f9a86_idx"),
        ),
    ]
